__version__ = "1.1.1"

import sys
from meshroom.core import desc
from ..common import node

class Tawny(node.MicmacNode, desc.CommandLineNode):
    commandLine = 'mm3d Tawny {orthoDirectoryValue} {allParams}'
    documentation = 'Tawny'

    inputs = [
        desc.File(
            name='projectDirectory',
            label='Project Directory',
            description='Project Directory.',
            value="",
            group='', # required to execute mm3d command line
            invalidate=True,
        ),
        desc.File(
            name='orthoDirectory',
            label='Ortho Directory',
            description="Ortho directory",
            group='', # unnamed parameter
            invalidate=True,
            value="",
        ),
        desc.BoolParam(
            name='RadiomEgal',
            label='Radiom Egal',
            description="Perform or not radiometric egalization",
            invalidate=True,
            value=True,
        ),
        desc.BoolParam(
            name='setDEq',
            label='Set DEq',
            description="Set DEq.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.IntParam(
            name='DEq',
            label='DEq',
            description="Degree of equalization",
            enabled=lambda node: node.setDEq.value,
            invalidate=True,
            value=1,
            range=(-sys.maxsize, sys.maxsize, 1),
            advanced=True,
        ),
        desc.BoolParam(
            name='setDEqXY',
            label='Set DEqXY',
            description="Set DEqXY.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.GroupAttribute(
            name='DEqXY',
            label='DEqXY',
            description="Degree of equalization, if diff in X and Y",
            brackets='[]',
            joinChar=',',
            enabled=lambda node: node.setDEqXY.value,
            advanced=True,
            groupDesc=[
            desc.IntParam(
                name="x",
                label="X",
                description="x.",
                value=0,
                range=(-sys.maxsize, sys.maxsize, 1),
                invalidate=True,
            ),
            desc.IntParam(
                name="y",
                label="Y",
                description="y.",
                value=0,
                range=(-sys.maxsize, sys.maxsize, 1),
                invalidate=True,
            ),
        ]),
        desc.BoolParam(
            name='setAddCste',
            label='Set Add Cste',
            description="Set add cste.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.BoolParam(
            name='AddCste',
            label='Add Cste',
            description="Add unknown constant for equalization",
            enabled=lambda node: node.setAddCste.value,
            invalidate=True,
            value=False,
            advanced=True,
        ),
        desc.BoolParam(
            name='setDegRap',
            label='Set DegRap',
            description="Set DegRap.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.IntParam(
            name='DegRap',
            label='Deg Rap',
            description="Degree of rappel to initial values",
            enabled=lambda node: node.setDegRap.value,
            invalidate=True,
            value=0,
            range=(-sys.maxsize, sys.maxsize, 1),
            advanced=True,
        ),
        desc.BoolParam(
            name='setDegRapXY',
            label='Set DegRapXY',
            description="Set DegRapXY.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.GroupAttribute(
            name='DegRapXY',
            label='Deg Rap X Y',
            description="Degree of rappel to initial values",
            brackets='[]',
            joinChar=',',
            enabled=lambda node: node.setDegRapXY.value,
            advanced=True,
            groupDesc=[
            desc.IntParam(
                name="x",
                label="X",
                description="x.",
                value=0,
                range=(-sys.maxsize, sys.maxsize, 1),
                invalidate=True,
            ),
            desc.IntParam(
                name="y",
                label="Y",
                description="y.",
                value=0,
                range=(-sys.maxsize, sys.maxsize, 1),
                invalidate=True,
            ),
        ]),
        desc.BoolParam(
            name='setRGP',
            label='Set RGP',
            description="Set RGP.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.BoolParam(
            name='RGP',
            label='RGP',
            description="Rappel glob on physically equalized",
            enabled=lambda node: node.setRGP.value,
            invalidate=True,
            value=True,
            advanced=True,
        ),
        desc.BoolParam(
            name='setDynG',
            label='Set DynG',
            description="Set DynG.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.FloatParam(
            name='DynG',
            label='DynG',
            description="Global Dynamic (to correct saturation problems)",
            enabled=lambda node: node.setDynG.value,
            invalidate=True,
            value=0.0,
            range=(-float('inf'), float('inf'), 0.01),
            advanced=True,
        ),
        desc.BoolParam(
            name='setImPrio',
            label='Set Im Prio',
            description="Set Im Prio.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.StringParam(
            name='ImPrio',
            label='Im Prio',
            description="Pattern of image with high prio",
            enabled=lambda node: node.setImPrio.value,
            invalidate=True,
            value=".*",
            advanced=True,
        ),
        desc.BoolParam(
            name='setSzV',
            label='Set SzV',
            description="Set SzV.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.IntParam(
            name='SzV',
            label='SzV',
            description="Size of Window for equalization (1 means 3x3)",
            enabled=lambda node: node.setSzV.value,
            invalidate=True,
            value=1,
            range=(-sys.maxsize, sys.maxsize, 1),
            advanced=True,
        ),
        desc.BoolParam(
            name='setCorThr',
            label='Set Cor Thr',
            description="Set Cor Thr.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.FloatParam(
            name='CorThr',
            label='Cor Thr',
            description="Threshold of correlation to validate homologous",
            enabled=lambda node: node.setCorThr.value,
            invalidate=True,
            value=0.7,
            range=(-float('inf'), float('inf'), 0.01),
            advanced=True,
        ),
        desc.BoolParam(
            name='setNbPerIm',
            label='Set Nb Per Im',
            description="Set Nb Per Im.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.FloatParam(
            name='NbPerIm',
            label='Nb Per Im',
            description="Average number of point per image",
            enabled=lambda node: node.setNbPerIm.value,
            invalidate=True,
            value=1e4,
            range=(-float('inf'), float('inf'), 0.01),
            advanced=True,
        ),
        desc.BoolParam(
            name='setL1F',
            label='Set L1 F',
            description="Set L1 F.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.BoolParam(
            name='L1F',
            label='L1 F',
            description="Do L1 Filter on couple",
            enabled=lambda node: node.setL1F.value,
            invalidate=True,
            value=True,
            advanced=True,
        ),
        desc.BoolParam(
            name='setSatThresh',
            label='Set Sat Thresh',
            description="Set Sat Thresh.",
            invalidate=True,
            value=False,
            group='',
            advanced=True,
        ),
        desc.FloatParam(
            name='SatThresh',
            label='Sat Thresh',
            description="Threshold determining saturation value (pixel >SatThresh will be ignored)",
            enabled=lambda node: node.setSatThresh.value,
            invalidate=True,
            value=0.0,
            range=(-float('inf'), float('inf'), 0.01),
            advanced=True,
        ),
    ]

    outputs = [
        desc.File(
            name='Out',
            label='Orthophoto',
            description="Name of output file (in the folder)",
            invalidate=False,
            value="Orthophotomosaic.tif",
        ),
    ]
